env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - solid
  - only-warn
extends:
  - plugin:solid/recommended
  - 'plugin:@typescript-eslint/recommended'
rules:
  semi: [ 1, always ]
  no-multiple-empty-lines: [ 1, { max: 2, maxEOF: 0 } ]
  prefer-const: 1
  arrow-parens: [1, always]
  indent: [1, tab, { SwitchCase: 1 }]
  comma-dangle: [1, always-multiline]
  quote-props: [1, as-needed]
  object-curly-spacing: [1, always]
  object-curly-newline: [1, { multiline: true, consistent: true }]
  no-trailing-spaces: 1
  no-console: [1, { allow: [warn, error] }]
  quotes: [1, single]
  jsx-quotes: 1
  key-spacing: [ 1, { align: value } ]

  '@typescript-eslint/key-spacing': [ 1, { align: value } ]
  '@typescript-eslint/no-unused-vars': 1
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/ban-types': 1

  react/jsx-max-props-per-line: [1, { maximum: 1, when: multiline }]
  react/jsx-closing-bracket-location: 1
  react/jsx-one-expression-per-line: [1, { allow: single-child }]
  react/jsx-indent: [1, tab]
  react/jsx-first-prop-new-line: 1
  react/button-has-type: [1, { reset: true }]
  react/jsx-tag-spacing: 1

  solid/jsx-no-undef: 0
  solid/self-closing-comp: 0
  solid/reactivity: 0

